# Generated by Django 5.0.6 on 2024-05-20 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Contact_No', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('Address', models.CharField(max_length=100)),
            ],
        ),
    ]
